spring:
  datasource:
#    url: jdbc:h2:file:./studentDB
    url: jdbc:h2:mem:./studentDB
    driverClassName: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
#
#  jpa:
#    properties:
#      hibernate:
##        dialect: org.hibernate.dialect.MySQL5InnoDBDialect
##        ddl-auto: none
##        format_sql: true
#        generate_statistics: false
#    show-sql: true

